version: '3'

services:
  app:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - memcached
      - grpc
    networks:
      - app-tier
    environment:
      - PORT=8080
      - MC_PORT=11211
      - GRPC_PORT=5001
  grpc:
    container_name: grpc
    ports:
      - "5001:5001"
    restart: always
  memcached:
    container_name: memcached
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
    networks:
      - app-tier
    environment:
      - MEMCACHED_CACHE_SIZE=128


networks:
  app-tier: